version: "0.5"

processes:
  zenohd-router:
    command: >
      clover-zenoh
    availability:
      restart: "always"
  clover-hub:
    command: >
      clover-hub run server
    availability:
      restart: "on_failure"
    depends_on:
      zenohd-router:
        condition: process_started
