[toolchain]
channel = "nightly-2026-02-25"

targets = [
  # Linux
  "x86_64-unknown-linux-gnu",
  "aarch64-unknown-linux-gnu",

  # iOS
  "aarch64-apple-ios",
  "x86_64-apple-ios",
  "aarch64-apple-ios-sim",

  # Android
  "armv7-linux-androideabi",
  "i686-linux-android",
  "aarch64-linux-android",
  "x86_64-linux-android",

  # Mac
  "x86_64-apple-darwin",
  "aarch64-apple-darwin",

  # Windows
  "x86_64-pc-windows-gnu",

  # WebAssembly
  "wasm32-unknown-unknown",

  # Pi Pico 2
  "thumbv6m-none-eabi"
]
