[target.x86_64-unknown-linux-gnu]
# linker = "clang"
rustflags = [
  # (Nightly) Make the current crate share its generic instantiations
  "-Zshare-generics=y",
  # Make sure that tokio console works
  "--cfg",
  "tokio_unstable"
]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# runner = "probe-rs run --chip RP2040" # for jtag
runner = "elf2uf2-rs --deploy --serial --verbose" # for elf2uf2

rustflags = [
  "-C", "panic=abort",
]
