[package]
name = "spanner-desktop"
version = "1.0.0"
edition = "2021"

[dependencies]
cxx = "1.0.131"
cxx-qt = "0.7.0"
cxx-qt-lib = { version = "0.7.0", features = ["qt_full"] }

[build-dependencies]
cxx-qt-build = { version = "0.7.0", features = [ "link_qt_object_files" ] }
